### ISSUE TITLE
Create Sample Application

### ISSUE THREAD

**Issue by ajamaica** [metaplex-foundation/metaplex-android#16]
**Is your feature request related to a problem? Please describe.**
There is no sample app that can show a reference implementation for the SDK usage. 

**Describe the solution you'd like**
We need a Sample App that can use a Identity Driver to list NFTs from on-chain queries. This app has to run on Android latest app and use SPM to load the application.

**Comment by dreamchaser96** [comment]
Could you please do simple WIKI with simple examples on how to use this library? Same with Solana.kt, really would need simple guide on it :)

**Comment by ajamaica** [comment]
@dreamchaser96 I just uploaded the sample app. I am doing the README. I am focusing now that I finish on documentation.
