### ISSUE TITLE
Cannot import Solana library via implementation 'com.solana:solana:1.1.5'

### ISSUE THREAD

**Issue by dreamchaser96** [metaplex-foundation/metaplex-android#35]
Hey, I've been trying to launch sample app, but it fails because sample project cannot get Solana.kt libraries in your posted way. Pictures represent my code (deleted github token for security reasons).  Please help.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/18498136/170445216-4d1c4bc7-2af0-43e9-9bdd-4649f74eb6f7.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/18498136/170445260-e92e3c05-1305-452c-8e59-86455727e817.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/18498136/170445324-d34798c2-39f2-4a29-9275-77cbaf35da37.png">

**Comment by ajamaica** [comment]
Put the token directly not inside the system.getenv or add envase with those names. 

Getenv is looking for a key xx on you system env
