### ISSUE TITLE
Use Jitpack for gradle dependencies

### ISSUE THREAD

**Issue by creativedrewy** [metaplex-foundation/metaplex-android#48]
I would suggest using Jitpack to make this library available as gradle dependencies. If you make both SolanaKT and this repo use it, people who want to add this repo as a gradle dep in their projects won't have to setup a Github token and manage that way. They would just have to add jitpack as a maven endpoint.

I forked SolanaKT and this repo and got Jitpack working for my forks. It would be awesome if the official libs did the same!

**Comment by Funkatronics** [comment]
As you saw @creativedrewy, [version 1.1.1](https://github.com/metaplex-foundation/metaplex-android/releases/tag/1.1.1) and onward will be available through JitPack. Thanks for the suggestion!
